package com.wqp.aiot.edge.stream.stream.netty;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aiot_sense_data.proto

public final class SenseDeviceProtof {
  private SenseDeviceProtof() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SenseDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SenseData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 产品唯一标识
     * </pre>
     *
     * <code>string productsn = 100;</code>
     */
    String getProductsn();
    /**
     * <pre>
     * 产品唯一标识
     * </pre>
     *
     * <code>string productsn = 100;</code>
     */
    com.google.protobuf.ByteString
        getProductsnBytes();

    /**
     * <pre>
     * 边缘设备序列号
     * </pre>
     *
     * <code>string edgesn = 101;</code>
     */
    String getEdgesn();
    /**
     * <pre>
     * 边缘设备序列号
     * </pre>
     *
     * <code>string edgesn = 101;</code>
     */
    com.google.protobuf.ByteString
        getEdgesnBytes();

    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    java.util.List<SenseData.DeviceData>
        getDevicedataList();
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    SenseData.DeviceData getDevicedata(int index);
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    int getDevicedataCount();
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    java.util.List<? extends SenseData.DeviceDataOrBuilder>
        getDevicedataOrBuilderList();
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    SenseData.DeviceDataOrBuilder getDevicedataOrBuilder(
            int index);

    /**
     * <pre>
     * 上传时间
     * </pre>
     *
     * <code>string uploadtime = 103;</code>
     */
    String getUploadtime();
    /**
     * <pre>
     * 上传时间
     * </pre>
     *
     * <code>string uploadtime = 103;</code>
     */
    com.google.protobuf.ByteString
        getUploadtimeBytes();
  }
  /**
   * Protobuf type {@code SenseData}
   */
  public  static final class SenseData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SenseData)
      SenseDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SenseData.newBuilder() to construct.
    private SenseData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SenseData() {
      productsn_ = "";
      edgesn_ = "";
      devicedata_ = java.util.Collections.emptyList();
      uploadtime_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SenseData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SenseData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 802: {
              String s = input.readStringRequireUtf8();

              productsn_ = s;
              break;
            }
            case 810: {
              String s = input.readStringRequireUtf8();

              edgesn_ = s;
              break;
            }
            case 818: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                devicedata_ = new java.util.ArrayList<DeviceData>();
                mutable_bitField0_ |= 0x00000001;
              }
              devicedata_.add(
                  input.readMessage(DeviceData.parser(), extensionRegistry));
              break;
            }
            case 826: {
              String s = input.readStringRequireUtf8();

              uploadtime_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          devicedata_ = java.util.Collections.unmodifiableList(devicedata_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SenseDeviceProtof.internal_static_SenseData_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SenseDeviceProtof.internal_static_SenseData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SenseData.class, Builder.class);
    }

    public interface DeviceDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SenseData.DeviceData)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * 传感设备唯一标识
       * </pre>
       *
       * <code>string sn = 100;</code>
       */
      String getSn();
      /**
       * <pre>
       * 传感设备唯一标识
       * </pre>
       *
       * <code>string sn = 100;</code>
       */
      com.google.protobuf.ByteString
          getSnBytes();

      /**
       * <pre>
       * 传感设备版本
       * </pre>
       *
       * <code>string version = 101;</code>
       */
      String getVersion();
      /**
       * <pre>
       * 传感设备版本
       * </pre>
       *
       * <code>string version = 101;</code>
       */
      com.google.protobuf.ByteString
          getVersionBytes();

      /**
       * <pre>
       * 搜集时间
       * </pre>
       *
       * <code>string gathertime = 102;</code>
       */
      String getGathertime();
      /**
       * <pre>
       * 搜集时间
       * </pre>
       *
       * <code>string gathertime = 102;</code>
       */
      com.google.protobuf.ByteString
          getGathertimeBytes();

      /**
       * <pre>
       * 数据名称
       * </pre>
       *
       * <code>string dataname = 103;</code>
       */
      String getDataname();
      /**
       * <pre>
       * 数据名称
       * </pre>
       *
       * <code>string dataname = 103;</code>
       */
      com.google.protobuf.ByteString
          getDatanameBytes();

      /**
       * <pre>
       * 数据值
       * </pre>
       *
       * <code>string datavalue = 104;</code>
       */
      String getDatavalue();
      /**
       * <pre>
       * 数据值
       * </pre>
       *
       * <code>string datavalue = 104;</code>
       */
      com.google.protobuf.ByteString
          getDatavalueBytes();
    }
    /**
     * <pre>
     * 传感设备数据定义
     * </pre>
     *
     * Protobuf type {@code SenseData.DeviceData}
     */
    public  static final class DeviceData extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:SenseData.DeviceData)
        DeviceDataOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DeviceData.newBuilder() to construct.
      private DeviceData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DeviceData() {
        sn_ = "";
        version_ = "";
        gathertime_ = "";
        dataname_ = "";
        datavalue_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new DeviceData();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DeviceData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 802: {
                String s = input.readStringRequireUtf8();

                sn_ = s;
                break;
              }
              case 810: {
                String s = input.readStringRequireUtf8();

                version_ = s;
                break;
              }
              case 818: {
                String s = input.readStringRequireUtf8();

                gathertime_ = s;
                break;
              }
              case 826: {
                String s = input.readStringRequireUtf8();

                dataname_ = s;
                break;
              }
              case 834: {
                String s = input.readStringRequireUtf8();

                datavalue_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SenseDeviceProtof.internal_static_SenseData_DeviceData_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SenseDeviceProtof.internal_static_SenseData_DeviceData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeviceData.class, Builder.class);
      }

      public static final int SN_FIELD_NUMBER = 100;
      private volatile Object sn_;
      /**
       * <pre>
       * 传感设备唯一标识
       * </pre>
       *
       * <code>string sn = 100;</code>
       */
      public String getSn() {
        Object ref = sn_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sn_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 传感设备唯一标识
       * </pre>
       *
       * <code>string sn = 100;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VERSION_FIELD_NUMBER = 101;
      private volatile Object version_;
      /**
       * <pre>
       * 传感设备版本
       * </pre>
       *
       * <code>string version = 101;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 传感设备版本
       * </pre>
       *
       * <code>string version = 101;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int GATHERTIME_FIELD_NUMBER = 102;
      private volatile Object gathertime_;
      /**
       * <pre>
       * 搜集时间
       * </pre>
       *
       * <code>string gathertime = 102;</code>
       */
      public String getGathertime() {
        Object ref = gathertime_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          gathertime_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 搜集时间
       * </pre>
       *
       * <code>string gathertime = 102;</code>
       */
      public com.google.protobuf.ByteString
          getGathertimeBytes() {
        Object ref = gathertime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          gathertime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATANAME_FIELD_NUMBER = 103;
      private volatile Object dataname_;
      /**
       * <pre>
       * 数据名称
       * </pre>
       *
       * <code>string dataname = 103;</code>
       */
      public String getDataname() {
        Object ref = dataname_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dataname_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 数据名称
       * </pre>
       *
       * <code>string dataname = 103;</code>
       */
      public com.google.protobuf.ByteString
          getDatanameBytes() {
        Object ref = dataname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATAVALUE_FIELD_NUMBER = 104;
      private volatile Object datavalue_;
      /**
       * <pre>
       * 数据值
       * </pre>
       *
       * <code>string datavalue = 104;</code>
       */
      public String getDatavalue() {
        Object ref = datavalue_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          datavalue_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 数据值
       * </pre>
       *
       * <code>string datavalue = 104;</code>
       */
      public com.google.protobuf.ByteString
          getDatavalueBytes() {
        Object ref = datavalue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          datavalue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getSnBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 100, sn_);
        }
        if (!getVersionBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 101, version_);
        }
        if (!getGathertimeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 102, gathertime_);
        }
        if (!getDatanameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 103, dataname_);
        }
        if (!getDatavalueBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 104, datavalue_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getSnBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(100, sn_);
        }
        if (!getVersionBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(101, version_);
        }
        if (!getGathertimeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(102, gathertime_);
        }
        if (!getDatanameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(103, dataname_);
        }
        if (!getDatavalueBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(104, datavalue_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof DeviceData)) {
          return super.equals(obj);
        }
        DeviceData other = (DeviceData) obj;

        if (!getSn()
            .equals(other.getSn())) return false;
        if (!getVersion()
            .equals(other.getVersion())) return false;
        if (!getGathertime()
            .equals(other.getGathertime())) return false;
        if (!getDataname()
            .equals(other.getDataname())) return false;
        if (!getDatavalue()
            .equals(other.getDatavalue())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SN_FIELD_NUMBER;
        hash = (53 * hash) + getSn().hashCode();
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion().hashCode();
        hash = (37 * hash) + GATHERTIME_FIELD_NUMBER;
        hash = (53 * hash) + getGathertime().hashCode();
        hash = (37 * hash) + DATANAME_FIELD_NUMBER;
        hash = (53 * hash) + getDataname().hashCode();
        hash = (37 * hash) + DATAVALUE_FIELD_NUMBER;
        hash = (53 * hash) + getDatavalue().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static DeviceData parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DeviceData parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DeviceData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DeviceData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DeviceData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DeviceData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DeviceData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DeviceData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static DeviceData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static DeviceData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static DeviceData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DeviceData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(DeviceData prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * 传感设备数据定义
       * </pre>
       *
       * Protobuf type {@code SenseData.DeviceData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:SenseData.DeviceData)
          DeviceDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SenseDeviceProtof.internal_static_SenseData_DeviceData_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SenseDeviceProtof.internal_static_SenseData_DeviceData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  DeviceData.class, Builder.class);
        }

        // Construct using SenseDeviceProtof.SenseData.DeviceData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          sn_ = "";

          version_ = "";

          gathertime_ = "";

          dataname_ = "";

          datavalue_ = "";

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SenseDeviceProtof.internal_static_SenseData_DeviceData_descriptor;
        }

        @Override
        public DeviceData getDefaultInstanceForType() {
          return DeviceData.getDefaultInstance();
        }

        @Override
        public DeviceData build() {
          DeviceData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public DeviceData buildPartial() {
          DeviceData result = new DeviceData(this);
          result.sn_ = sn_;
          result.version_ = version_;
          result.gathertime_ = gathertime_;
          result.dataname_ = dataname_;
          result.datavalue_ = datavalue_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof DeviceData) {
            return mergeFrom((DeviceData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(DeviceData other) {
          if (other == DeviceData.getDefaultInstance()) return this;
          if (!other.getSn().isEmpty()) {
            sn_ = other.sn_;
            onChanged();
          }
          if (!other.getVersion().isEmpty()) {
            version_ = other.version_;
            onChanged();
          }
          if (!other.getGathertime().isEmpty()) {
            gathertime_ = other.gathertime_;
            onChanged();
          }
          if (!other.getDataname().isEmpty()) {
            dataname_ = other.dataname_;
            onChanged();
          }
          if (!other.getDatavalue().isEmpty()) {
            datavalue_ = other.datavalue_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          DeviceData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (DeviceData) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private Object sn_ = "";
        /**
         * <pre>
         * 传感设备唯一标识
         * </pre>
         *
         * <code>string sn = 100;</code>
         */
        public String getSn() {
          Object ref = sn_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            sn_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 传感设备唯一标识
         * </pre>
         *
         * <code>string sn = 100;</code>
         */
        public com.google.protobuf.ByteString
            getSnBytes() {
          Object ref = sn_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            sn_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 传感设备唯一标识
         * </pre>
         *
         * <code>string sn = 100;</code>
         */
        public Builder setSn(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          sn_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 传感设备唯一标识
         * </pre>
         *
         * <code>string sn = 100;</code>
         */
        public Builder clearSn() {
          
          sn_ = getDefaultInstance().getSn();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 传感设备唯一标识
         * </pre>
         *
         * <code>string sn = 100;</code>
         */
        public Builder setSnBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          sn_ = value;
          onChanged();
          return this;
        }

        private Object version_ = "";
        /**
         * <pre>
         * 传感设备版本
         * </pre>
         *
         * <code>string version = 101;</code>
         */
        public String getVersion() {
          Object ref = version_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            version_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 传感设备版本
         * </pre>
         *
         * <code>string version = 101;</code>
         */
        public com.google.protobuf.ByteString
            getVersionBytes() {
          Object ref = version_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            version_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 传感设备版本
         * </pre>
         *
         * <code>string version = 101;</code>
         */
        public Builder setVersion(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          version_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 传感设备版本
         * </pre>
         *
         * <code>string version = 101;</code>
         */
        public Builder clearVersion() {
          
          version_ = getDefaultInstance().getVersion();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 传感设备版本
         * </pre>
         *
         * <code>string version = 101;</code>
         */
        public Builder setVersionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          version_ = value;
          onChanged();
          return this;
        }

        private Object gathertime_ = "";
        /**
         * <pre>
         * 搜集时间
         * </pre>
         *
         * <code>string gathertime = 102;</code>
         */
        public String getGathertime() {
          Object ref = gathertime_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            gathertime_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 搜集时间
         * </pre>
         *
         * <code>string gathertime = 102;</code>
         */
        public com.google.protobuf.ByteString
            getGathertimeBytes() {
          Object ref = gathertime_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            gathertime_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 搜集时间
         * </pre>
         *
         * <code>string gathertime = 102;</code>
         */
        public Builder setGathertime(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          gathertime_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 搜集时间
         * </pre>
         *
         * <code>string gathertime = 102;</code>
         */
        public Builder clearGathertime() {
          
          gathertime_ = getDefaultInstance().getGathertime();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 搜集时间
         * </pre>
         *
         * <code>string gathertime = 102;</code>
         */
        public Builder setGathertimeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          gathertime_ = value;
          onChanged();
          return this;
        }

        private Object dataname_ = "";
        /**
         * <pre>
         * 数据名称
         * </pre>
         *
         * <code>string dataname = 103;</code>
         */
        public String getDataname() {
          Object ref = dataname_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            dataname_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 数据名称
         * </pre>
         *
         * <code>string dataname = 103;</code>
         */
        public com.google.protobuf.ByteString
            getDatanameBytes() {
          Object ref = dataname_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            dataname_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 数据名称
         * </pre>
         *
         * <code>string dataname = 103;</code>
         */
        public Builder setDataname(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          dataname_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 数据名称
         * </pre>
         *
         * <code>string dataname = 103;</code>
         */
        public Builder clearDataname() {
          
          dataname_ = getDefaultInstance().getDataname();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 数据名称
         * </pre>
         *
         * <code>string dataname = 103;</code>
         */
        public Builder setDatanameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          dataname_ = value;
          onChanged();
          return this;
        }

        private Object datavalue_ = "";
        /**
         * <pre>
         * 数据值
         * </pre>
         *
         * <code>string datavalue = 104;</code>
         */
        public String getDatavalue() {
          Object ref = datavalue_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            datavalue_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         * 数据值
         * </pre>
         *
         * <code>string datavalue = 104;</code>
         */
        public com.google.protobuf.ByteString
            getDatavalueBytes() {
          Object ref = datavalue_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            datavalue_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 数据值
         * </pre>
         *
         * <code>string datavalue = 104;</code>
         */
        public Builder setDatavalue(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          datavalue_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 数据值
         * </pre>
         *
         * <code>string datavalue = 104;</code>
         */
        public Builder clearDatavalue() {
          
          datavalue_ = getDefaultInstance().getDatavalue();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 数据值
         * </pre>
         *
         * <code>string datavalue = 104;</code>
         */
        public Builder setDatavalueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          datavalue_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:SenseData.DeviceData)
      }

      // @@protoc_insertion_point(class_scope:SenseData.DeviceData)
      private static final DeviceData DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new DeviceData();
      }

      public static DeviceData getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DeviceData>
          PARSER = new com.google.protobuf.AbstractParser<DeviceData>() {
        @Override
        public DeviceData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DeviceData(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DeviceData> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<DeviceData> getParserForType() {
        return PARSER;
      }

      @Override
      public DeviceData getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PRODUCTSN_FIELD_NUMBER = 100;
    private volatile Object productsn_;
    /**
     * <pre>
     * 产品唯一标识
     * </pre>
     *
     * <code>string productsn = 100;</code>
     */
    public String getProductsn() {
      Object ref = productsn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        productsn_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 产品唯一标识
     * </pre>
     *
     * <code>string productsn = 100;</code>
     */
    public com.google.protobuf.ByteString
        getProductsnBytes() {
      Object ref = productsn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        productsn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EDGESN_FIELD_NUMBER = 101;
    private volatile Object edgesn_;
    /**
     * <pre>
     * 边缘设备序列号
     * </pre>
     *
     * <code>string edgesn = 101;</code>
     */
    public String getEdgesn() {
      Object ref = edgesn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        edgesn_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 边缘设备序列号
     * </pre>
     *
     * <code>string edgesn = 101;</code>
     */
    public com.google.protobuf.ByteString
        getEdgesnBytes() {
      Object ref = edgesn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        edgesn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEDATA_FIELD_NUMBER = 102;
    private java.util.List<DeviceData> devicedata_;
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    public java.util.List<DeviceData> getDevicedataList() {
      return devicedata_;
    }
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    public java.util.List<? extends DeviceDataOrBuilder>
        getDevicedataOrBuilderList() {
      return devicedata_;
    }
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    public int getDevicedataCount() {
      return devicedata_.size();
    }
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    public DeviceData getDevicedata(int index) {
      return devicedata_.get(index);
    }
    /**
     * <pre>
     * 传感设备数据
     * </pre>
     *
     * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
     */
    public DeviceDataOrBuilder getDevicedataOrBuilder(
        int index) {
      return devicedata_.get(index);
    }

    public static final int UPLOADTIME_FIELD_NUMBER = 103;
    private volatile Object uploadtime_;
    /**
     * <pre>
     * 上传时间
     * </pre>
     *
     * <code>string uploadtime = 103;</code>
     */
    public String getUploadtime() {
      Object ref = uploadtime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uploadtime_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 上传时间
     * </pre>
     *
     * <code>string uploadtime = 103;</code>
     */
    public com.google.protobuf.ByteString
        getUploadtimeBytes() {
      Object ref = uploadtime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uploadtime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProductsnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 100, productsn_);
      }
      if (!getEdgesnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 101, edgesn_);
      }
      for (int i = 0; i < devicedata_.size(); i++) {
        output.writeMessage(102, devicedata_.get(i));
      }
      if (!getUploadtimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 103, uploadtime_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProductsnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(100, productsn_);
      }
      if (!getEdgesnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(101, edgesn_);
      }
      for (int i = 0; i < devicedata_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, devicedata_.get(i));
      }
      if (!getUploadtimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(103, uploadtime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SenseData)) {
        return super.equals(obj);
      }
      SenseData other = (SenseData) obj;

      if (!getProductsn()
          .equals(other.getProductsn())) return false;
      if (!getEdgesn()
          .equals(other.getEdgesn())) return false;
      if (!getDevicedataList()
          .equals(other.getDevicedataList())) return false;
      if (!getUploadtime()
          .equals(other.getUploadtime())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTSN_FIELD_NUMBER;
      hash = (53 * hash) + getProductsn().hashCode();
      hash = (37 * hash) + EDGESN_FIELD_NUMBER;
      hash = (53 * hash) + getEdgesn().hashCode();
      if (getDevicedataCount() > 0) {
        hash = (37 * hash) + DEVICEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getDevicedataList().hashCode();
      }
      hash = (37 * hash) + UPLOADTIME_FIELD_NUMBER;
      hash = (53 * hash) + getUploadtime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SenseData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SenseData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SenseData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SenseData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SenseData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SenseData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SenseData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SenseData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SenseData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SenseData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SenseData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SenseData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SenseData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SenseData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SenseData)
        SenseDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SenseDeviceProtof.internal_static_SenseData_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SenseDeviceProtof.internal_static_SenseData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SenseData.class, Builder.class);
      }

      // Construct using SenseDeviceProtof.SenseData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDevicedataFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        productsn_ = "";

        edgesn_ = "";

        if (devicedataBuilder_ == null) {
          devicedata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          devicedataBuilder_.clear();
        }
        uploadtime_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SenseDeviceProtof.internal_static_SenseData_descriptor;
      }

      @Override
      public SenseData getDefaultInstanceForType() {
        return SenseData.getDefaultInstance();
      }

      @Override
      public SenseData build() {
        SenseData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SenseData buildPartial() {
        SenseData result = new SenseData(this);
        int from_bitField0_ = bitField0_;
        result.productsn_ = productsn_;
        result.edgesn_ = edgesn_;
        if (devicedataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            devicedata_ = java.util.Collections.unmodifiableList(devicedata_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.devicedata_ = devicedata_;
        } else {
          result.devicedata_ = devicedataBuilder_.build();
        }
        result.uploadtime_ = uploadtime_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SenseData) {
          return mergeFrom((SenseData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SenseData other) {
        if (other == SenseData.getDefaultInstance()) return this;
        if (!other.getProductsn().isEmpty()) {
          productsn_ = other.productsn_;
          onChanged();
        }
        if (!other.getEdgesn().isEmpty()) {
          edgesn_ = other.edgesn_;
          onChanged();
        }
        if (devicedataBuilder_ == null) {
          if (!other.devicedata_.isEmpty()) {
            if (devicedata_.isEmpty()) {
              devicedata_ = other.devicedata_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDevicedataIsMutable();
              devicedata_.addAll(other.devicedata_);
            }
            onChanged();
          }
        } else {
          if (!other.devicedata_.isEmpty()) {
            if (devicedataBuilder_.isEmpty()) {
              devicedataBuilder_.dispose();
              devicedataBuilder_ = null;
              devicedata_ = other.devicedata_;
              bitField0_ = (bitField0_ & ~0x00000001);
              devicedataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDevicedataFieldBuilder() : null;
            } else {
              devicedataBuilder_.addAllMessages(other.devicedata_);
            }
          }
        }
        if (!other.getUploadtime().isEmpty()) {
          uploadtime_ = other.uploadtime_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SenseData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SenseData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object productsn_ = "";
      /**
       * <pre>
       * 产品唯一标识
       * </pre>
       *
       * <code>string productsn = 100;</code>
       */
      public String getProductsn() {
        Object ref = productsn_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          productsn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 产品唯一标识
       * </pre>
       *
       * <code>string productsn = 100;</code>
       */
      public com.google.protobuf.ByteString
          getProductsnBytes() {
        Object ref = productsn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          productsn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 产品唯一标识
       * </pre>
       *
       * <code>string productsn = 100;</code>
       */
      public Builder setProductsn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        productsn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 产品唯一标识
       * </pre>
       *
       * <code>string productsn = 100;</code>
       */
      public Builder clearProductsn() {
        
        productsn_ = getDefaultInstance().getProductsn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 产品唯一标识
       * </pre>
       *
       * <code>string productsn = 100;</code>
       */
      public Builder setProductsnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        productsn_ = value;
        onChanged();
        return this;
      }

      private Object edgesn_ = "";
      /**
       * <pre>
       * 边缘设备序列号
       * </pre>
       *
       * <code>string edgesn = 101;</code>
       */
      public String getEdgesn() {
        Object ref = edgesn_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          edgesn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 边缘设备序列号
       * </pre>
       *
       * <code>string edgesn = 101;</code>
       */
      public com.google.protobuf.ByteString
          getEdgesnBytes() {
        Object ref = edgesn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          edgesn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 边缘设备序列号
       * </pre>
       *
       * <code>string edgesn = 101;</code>
       */
      public Builder setEdgesn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        edgesn_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 边缘设备序列号
       * </pre>
       *
       * <code>string edgesn = 101;</code>
       */
      public Builder clearEdgesn() {
        
        edgesn_ = getDefaultInstance().getEdgesn();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 边缘设备序列号
       * </pre>
       *
       * <code>string edgesn = 101;</code>
       */
      public Builder setEdgesnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        edgesn_ = value;
        onChanged();
        return this;
      }

      private java.util.List<DeviceData> devicedata_ =
        java.util.Collections.emptyList();
      private void ensureDevicedataIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          devicedata_ = new java.util.ArrayList<DeviceData>(devicedata_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          DeviceData, DeviceData.Builder, DeviceDataOrBuilder> devicedataBuilder_;

      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public java.util.List<DeviceData> getDevicedataList() {
        if (devicedataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(devicedata_);
        } else {
          return devicedataBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public int getDevicedataCount() {
        if (devicedataBuilder_ == null) {
          return devicedata_.size();
        } else {
          return devicedataBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public DeviceData getDevicedata(int index) {
        if (devicedataBuilder_ == null) {
          return devicedata_.get(index);
        } else {
          return devicedataBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder setDevicedata(
          int index, DeviceData value) {
        if (devicedataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicedataIsMutable();
          devicedata_.set(index, value);
          onChanged();
        } else {
          devicedataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder setDevicedata(
          int index, DeviceData.Builder builderForValue) {
        if (devicedataBuilder_ == null) {
          ensureDevicedataIsMutable();
          devicedata_.set(index, builderForValue.build());
          onChanged();
        } else {
          devicedataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder addDevicedata(DeviceData value) {
        if (devicedataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicedataIsMutable();
          devicedata_.add(value);
          onChanged();
        } else {
          devicedataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder addDevicedata(
          int index, DeviceData value) {
        if (devicedataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDevicedataIsMutable();
          devicedata_.add(index, value);
          onChanged();
        } else {
          devicedataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder addDevicedata(
          DeviceData.Builder builderForValue) {
        if (devicedataBuilder_ == null) {
          ensureDevicedataIsMutable();
          devicedata_.add(builderForValue.build());
          onChanged();
        } else {
          devicedataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder addDevicedata(
          int index, DeviceData.Builder builderForValue) {
        if (devicedataBuilder_ == null) {
          ensureDevicedataIsMutable();
          devicedata_.add(index, builderForValue.build());
          onChanged();
        } else {
          devicedataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder addAllDevicedata(
          Iterable<? extends DeviceData> values) {
        if (devicedataBuilder_ == null) {
          ensureDevicedataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, devicedata_);
          onChanged();
        } else {
          devicedataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder clearDevicedata() {
        if (devicedataBuilder_ == null) {
          devicedata_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          devicedataBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public Builder removeDevicedata(int index) {
        if (devicedataBuilder_ == null) {
          ensureDevicedataIsMutable();
          devicedata_.remove(index);
          onChanged();
        } else {
          devicedataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public DeviceData.Builder getDevicedataBuilder(
          int index) {
        return getDevicedataFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public DeviceDataOrBuilder getDevicedataOrBuilder(
          int index) {
        if (devicedataBuilder_ == null) {
          return devicedata_.get(index);  } else {
          return devicedataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public java.util.List<? extends DeviceDataOrBuilder>
           getDevicedataOrBuilderList() {
        if (devicedataBuilder_ != null) {
          return devicedataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(devicedata_);
        }
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public DeviceData.Builder addDevicedataBuilder() {
        return getDevicedataFieldBuilder().addBuilder(
            DeviceData.getDefaultInstance());
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public DeviceData.Builder addDevicedataBuilder(
          int index) {
        return getDevicedataFieldBuilder().addBuilder(
            index, DeviceData.getDefaultInstance());
      }
      /**
       * <pre>
       * 传感设备数据
       * </pre>
       *
       * <code>repeated .SenseData.DeviceData devicedata = 102;</code>
       */
      public java.util.List<DeviceData.Builder>
           getDevicedataBuilderList() {
        return getDevicedataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          DeviceData, DeviceData.Builder, DeviceDataOrBuilder>
          getDevicedataFieldBuilder() {
        if (devicedataBuilder_ == null) {
          devicedataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              DeviceData, DeviceData.Builder, DeviceDataOrBuilder>(
                  devicedata_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          devicedata_ = null;
        }
        return devicedataBuilder_;
      }

      private Object uploadtime_ = "";
      /**
       * <pre>
       * 上传时间
       * </pre>
       *
       * <code>string uploadtime = 103;</code>
       */
      public String getUploadtime() {
        Object ref = uploadtime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uploadtime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 上传时间
       * </pre>
       *
       * <code>string uploadtime = 103;</code>
       */
      public com.google.protobuf.ByteString
          getUploadtimeBytes() {
        Object ref = uploadtime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uploadtime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 上传时间
       * </pre>
       *
       * <code>string uploadtime = 103;</code>
       */
      public Builder setUploadtime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uploadtime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 上传时间
       * </pre>
       *
       * <code>string uploadtime = 103;</code>
       */
      public Builder clearUploadtime() {
        
        uploadtime_ = getDefaultInstance().getUploadtime();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 上传时间
       * </pre>
       *
       * <code>string uploadtime = 103;</code>
       */
      public Builder setUploadtimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uploadtime_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SenseData)
    }

    // @@protoc_insertion_point(class_scope:SenseData)
    private static final SenseData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SenseData();
    }

    public static SenseData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SenseData>
        PARSER = new com.google.protobuf.AbstractParser<SenseData>() {
      @Override
      public SenseData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SenseData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SenseData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SenseData> getParserForType() {
      return PARSER;
    }

    @Override
    public SenseData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SenseData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SenseData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SenseData_DeviceData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SenseData_DeviceData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025aiot_sense_data.proto\"\321\001\n\tSenseData\022\021\n" +
      "\tproductsn\030d \001(\t\022\016\n\006edgesn\030e \001(\t\022)\n\ndevi" +
      "cedata\030f \003(\0132\025.SenseData.DeviceData\022\022\n\nu" +
      "ploadtime\030g \001(\t\032b\n\nDeviceData\022\n\n\002sn\030d \001(" +
      "\t\022\017\n\007version\030e \001(\t\022\022\n\ngathertime\030f \001(\t\022\020" +
      "\n\010dataname\030g \001(\t\022\021\n\tdatavalue\030h \001(\tB\023B\021S" +
      "enseDeviceProtofb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SenseData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SenseData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SenseData_descriptor,
        new String[] { "Productsn", "Edgesn", "Devicedata", "Uploadtime", });
    internal_static_SenseData_DeviceData_descriptor =
      internal_static_SenseData_descriptor.getNestedTypes().get(0);
    internal_static_SenseData_DeviceData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SenseData_DeviceData_descriptor,
        new String[] { "Sn", "Version", "Gathertime", "Dataname", "Datavalue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
